usb: f_fs: Fix build error caused by variable renaming
Upstream commit 86f8b0e brought a build error to CAF kernels because
ffs_log relies on `struct ffs_data *ffs` after macro expanding.

This fixes the following build error:

../drivers/usb/gadget/function/f_fs.c:3236:4: error: member reference base type 'int (int)' is not a structure or union
                        ffs_log("functionfs_bind returned %d", ret);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: LibXZR <xzr467706992@163.com>
Change-Id: I01bd7a1b0dae24b5520e79e93e4455dc696df251
Signed-off-by: firebird11 <hbgassel@gmail.com>
Signed-off-by: alanndz <alanndz@qmail.id>